
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Deki
 */
public class VeterinarskiObrazac extends javax.swing.JFrame {
        String gender;
    public VeterinarskiObrazac() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        show_user();
    }
    public ArrayList<User> userList(){
        ArrayList<User> usersList = new ArrayList<>();
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/veterinar_database","root","deki");
           String query1 = "SELECT * FROM klijenti_table";
           Statement st = conn.createStatement();
           ResultSet rs = st.executeQuery(query1);
           User user;
           while(rs.next()){
               user = new User(rs.getInt("id"), rs.getString("ime_ljubimca"), rs.getString("ime_vlasnika"), rs.getString("pol"), rs.getString("tegobe"), rs.getString("rasa"));
               usersList.add(user);
           }
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
        }
        return usersList;
    }
    public void show_user(){
        ArrayList<User> list = userList();
        DefaultTableModel model = (DefaultTableModel)jTable1_show_users.getModel();
        Object[] row = new Object[6];
        for(int i=0; i<list.size();i++){
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getImeLjubimca();
            row[2] = list.get(i).getImeVlasnika();
            row[3] = list.get(i).getPol();
            row[4] = list.get(i).getTegobe();
            row[5] = list.get(i).getRasa();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        ownerName = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        parasites = new javax.swing.JCheckBox();
        injury = new javax.swing.JCheckBox();
        species = new javax.swing.JComboBox<>();
        savebtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_show_users = new javax.swing.JTable();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ime ljubimca:");

        jLabel2.setText("Ime vlasnika:");

        jLabel3.setText("Pol:");

        jLabel4.setText("Tegobe:");

        jLabel5.setText("Rasa:");

        buttonGroup1.add(male);
        male.setText("Muski");

        buttonGroup1.add(female);
        female.setText("Zenski");

        parasites.setText("Paraziti");

        injury.setText("Povreda");

        species.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sijamska macka", "Bengalska macka", "Havana Braon", "Domaca macka" }));

        savebtn.setText("Sacuvaj");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        resetbtn.setText("Resetuj");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        jTable1_show_users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Ime ljubimca", "Ime vlasnika", "Pol", "Tegobe", "Rasa"
            }
        ));
        jTable1_show_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_show_usersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_show_users);

        updatebtn.setText("Azuriraj");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        deletebtn.setText("Obrisi");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(82, 82, 82)
                        .addComponent(species, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(parasites)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addComponent(injury))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(male)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(female))
                            .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ownerName, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ownerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(male)
                    .addComponent(female))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(parasites)
                    .addComponent(injury))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(species, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtn)
                    .addComponent(resetbtn)
                    .addComponent(updatebtn)
                    .addComponent(deletebtn))
                .addGap(22, 22, 22))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/veterinar_database","root","deki");
           String query = "insert into klijenti_table(ime_ljubimca, ime_vlasnika, pol, tegobe, rasa)values(?,?,?,?,?)";
           PreparedStatement pst = conn.prepareStatement(query);
           pst.setString(1, name.getText());
           pst.setString(2, ownerName.getText());
           if(male.isSelected()){
               gender = "Muski";
           }
           if(female.isSelected()){
               gender = "Zenski";
           }
           pst.setString(3, gender);
           String illness = "";
           if(parasites.isSelected()){
               illness += parasites.getText() + " ";
           }
            if(injury.isSelected()){
               illness += injury.getText() + " ";
           }
            pst.setString(4, illness);
            String race;
            race = species.getSelectedItem().toString();
            pst.setString(5, race);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jTable1_show_users.getModel();
            model.setRowCount(0);
            show_user();
            JOptionPane.showMessageDialog(null, "Ljubimac uspesno dodat u bazu podataka");
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_savebtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        name.setText("");
        ownerName.setText("");
        buttonGroup1.clearSelection();
        species.setSelectedIndex(0);
        parasites.setSelected(false);
        injury.setSelected(false);
    }//GEN-LAST:event_resetbtnActionPerformed

    private void jTable1_show_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_show_usersMouseClicked
        int i = jTable1_show_users.getSelectedRow();
        TableModel model = jTable1_show_users.getModel();
        name.setText(model.getValueAt(i, 1).toString());
        ownerName.setText(model.getValueAt(i, 2).toString());
        String catGender = model.getValueAt(i, 3).toString();
            if(catGender.equals("Muski")){
                male.setSelected(true);
            }else{
                female.setSelected(true);
            }
        String catTegobe = model.getValueAt(i, 4).toString();
            switch(catTegobe){
                case "Paraziti ":
                   parasites.setSelected(true);
                   injury.setSelected(false);
                   break;
            case "Povreda ":
                   parasites.setSelected(false);
                   injury.setSelected(true);
                   break; 
            default:
                   parasites.setSelected(true);
                   injury.setSelected(true);
            }
        String catRace = model.getValueAt(i, 5).toString();
            switch(catRace){
                case "Sijamska macka":
                    species.setSelectedIndex(0);
                    break;
                case "Bengalska macka":
                    species.setSelectedIndex(1);
                    break;
                case "Havana Braon":
                    species.setSelectedIndex(2);
                    break;
                case "Domaca macka":
                    species.setSelectedIndex(3);
            }
    }//GEN-LAST:event_jTable1_show_usersMouseClicked

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/veterinar_database","root","deki");
           int row = jTable1_show_users.getSelectedRow();
           String value = (jTable1_show_users.getModel().getValueAt(row, 0).toString());
           String query = "UPDATE klijenti_table SET ime_ljubimca=?, ime_vlasnika=?, pol=?, tegobe=?, rasa=? where id=" + value;
           PreparedStatement pst = conn.prepareStatement(query);
           pst.setString(1, name.getText());
           pst.setString(2, ownerName.getText());
           if(male.isSelected()){
               gender = "Muski";
           }
           if(female.isSelected()){
               gender = "Zenski";
           }
           pst.setString(3, gender);
           String illness = "";
           if(parasites.isSelected()){
               illness += parasites.getText() + " ";
           }
            if(injury.isSelected()){
               illness += injury.getText() + " ";
           }
            pst.setString(4, illness);
            String race;
            race = species.getSelectedItem().toString();
            pst.setString(5, race);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jTable1_show_users.getModel();
            model.setRowCount(0);
            show_user();
            JOptionPane.showMessageDialog(null, "Azuriranje uspesno");
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/veterinar_database","root","deki");
           int row = jTable1_show_users.getSelectedRow();
           String value = (jTable1_show_users.getModel().getValueAt(row, 0).toString());
           String query = "DELETE FROM klijenti_table where id=" + value;
           PreparedStatement pst = conn.prepareStatement(query);
           pst.executeUpdate();
           DefaultTableModel model = (DefaultTableModel)jTable1_show_users.getModel();
           model.setRowCount(0);
           show_user();
           JOptionPane.showMessageDialog(null, "Pacijent obrisan");
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_deletebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeterinarskiObrazac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeterinarskiObrazac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeterinarskiObrazac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeterinarskiObrazac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VeterinarskiObrazac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton deletebtn;
    private javax.swing.JRadioButton female;
    private javax.swing.JCheckBox injury;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_show_users;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JTextField ownerName;
    private javax.swing.JCheckBox parasites;
    private javax.swing.JButton resetbtn;
    private javax.swing.JButton savebtn;
    private javax.swing.JComboBox<String> species;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
